### ISSUE TITLE
Error: 'PushManager' in window always at false

### ISSUE THREAD

**Issue by Mester766** [bpolaszek/webpush-js#1]
Hello,
I wanted to get Push notifications working on my application, i've imported your WebPush Bundle but when i took the WebPush-js for the front-end, it always said me that my browser don't handle WebPush notifications.
I've tested every test of your isSupported function, and the reason is that, apparently, the 'PushManager' isn't found in window. I really need a little help here.

Thank you,

**Comment by bpolaszek** [comment]
Hello,

What's your browser / version / OS?
If you enter it manually in your browser console, which result does it produce?

<img width="183" alt="Capture d’écran 2020-03-19 à 07 08 13" src="https://user-images.githubusercontent.com/5569077/77036896-6f425480-69b0-11ea-9def-0788b9d15a2d.png">

**Comment by Mester766** [comment]
I tested it on Google Chrome and Firefox, normally the version of the browsers do handle Push notifications. I'm on windows.
I've already testes it manually in the browser console, that is how i found that was always at false.

**Comment by Mester766** [comment]
Hello,

did you have a clue yet of what my problem can be ? I really don't understand why my browser can't handle your bundle.
