### ISSUE TITLE
Compatibilty with Push Notification on Safari 16.1 (Mac) and Safari 16.4 (iOS)

### ISSUE THREAD

**Issue by rcournault** [bpolaszek/webpush-js#2]
the webpush package works very well on Chrome or Firefox, however on Safari 16.1 which is now compatible with push notifications (on mac) and with Ios 16.4 which will receive them, it does not seem to work

Unhandled Promise Rejection: NotSupportedError: The operation is not supported.
promiseEmptyOnRejected
promiseReaction Job

And the service worker is not register... any Idea ? Do you know where is the bug ?

**Comment by bpolaszek** [comment]
Hi @rcournault 👋 

It looks like Safari did not like the way we asked for Notification permissions.

There's an easiest way `Notification.requestPermission()` that has just been implemented, as of `0.4.2` - you can upgrade the package and it should work out of the box.

Unrelated: I also noticed that Safari won't display notifications when your VAPID auth have no valid `subject` field. Please ensure it has a correct `mailto:` or `https://` URN before sending notifications.
